export const adjektiver = [
  "BARBERT","BARKA","BARSK","BEIN","BISK","BRAV","BRYSK","DIGG","DJERV","DUS",
  "ENKEL","FALSK","FIN","FJASETE","FJERN","FJONG","FLINK","FRI","FRISK","FUL",
  "FYNDIG","FYRRIG","GLUPSK","GOD","GREI","HALV","HARM","HASTIG","HEL","HET",
  "HUL","KLEIN","KLINK","KLOK","KRAM","KRESEN","KUNSTIG","KVIKK","LANG","LAT",
  "LEKEN","LEKKER","LILLA","LODDEN","LUMPEN","LUNKEN","LUR","MODIG","MORSK","MUTT",
  "PEN","PIGG","PUSETE","RAGGETE","RAK","RAM","RAUS","ROSA","RUND","SABLA",
  "SART","SKARP","SLEM","SMAL","SMART","SMEKKER","SMIDIG","SMUL","SNEDIG","SNEVER",
  "SNILL","SNODIG","SNURRIG","SOLID","STAUT","STERK","STILIG","STOLT","STRAM","SUKRET",
  "SUNN","SUR","SYK","SYNLIG","TAUS","TETT","TRASIG","TRAVEL","TRENT","TRYGG",
  "TVERR","UJEVN","URBAN","VAKKER","VARM","VERDIG","VILL","VIMSETE","VOKSEN","VRIEN"
];

export const substantiver = [
  "AI","ALPAKKA","ANKEL","APP","BAJAS","BARBIE","BAUTA","HANDEL","BLOGG","BOM",
  "BONDE","BRIKKE","BRIS","BRO","BRYGGE","BY","CAPS","DIVA","DOKTOR","DUE",
  "ELSK","FEIL","FIDUS","FIKEN","FINGER","FJOMP","FLINKIS","FNATT","FRED","FRISKUS",
  "FRITYR","FRYD","FYSJ","GNU","HYTTE","ID","IRIS","ISSE","KAMERAT","KANAL",
  "KARPE","KI","KIME","KJERNE","KLOKKE","KLOVN","KNASK","KNEKK","KNIRK","KNOTT",
  "KNURR","KODE","KOK","KONSERT","KOS","KRISE","KRYPTO","KULTUR","LEG","LEK",
  "LEPPE","LOMME","LURV","LUTT","MASKIN","MORT","NATUR","NONNE","OMPA","PALL",
  "PARYKK","PEDAL","PEIS","PENGE","PILLE","PULS","PUST","RADIO","RAMP","ROCK",
  "ROSIN","RUNE","SANNHET","SEDDEL","SIDE","SLARK","SLARV","SLURV","SNUTE","SOL",
  "SPILLER","TANKE","TILLIT","TUR","TVIL","TYV","VAMP","VARE","VASK","VEKST"
];